"""Remove title column

Revision ID: 89b1faf6121e
Revises: e26b32b49a80
Create Date: 2024-12-19 08:18:49.272015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b1faf6121e'
down_revision = 'e26b32b49a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
