"""Add hashed IP address column

Revision ID: e26b32b49a80
Revises: e0e8ad40035c
Create Date: 2024-12-13 14:23:24.380482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26b32b49a80'
down_revision = 'e0e8ad40035c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
